services:
  - type: web
    name: graphql-color-api
    env: node
    plan: free
    buildCommand: |
      npm install
      npm run prisma:generate
      npm run build
      cp -r dist /opt/render/project/src/
    startCommand: node /opt/render/project/src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: "4000"