services:
  - type: web
    name: graphql-color-api
    env: node
    buildCommand: npm install && npm run prisma:generate && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: "4000"
    healthCheckPath: /health